# Generated by Django 4.0 on 2021-12-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopowner', '0002_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaReceipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mpesaReceiptNumber', models.CharField(max_length=10)),
                ('transactionDate', models.DateTimeField()),
                ('phoneNumber', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'mpesareceipts',
            },
        ),
    ]
